package viewGUI;

//import javafx.fxml.FXML;
//
//import javafx.scene.control.Button;
//
//import javafx.scene.control.TextField;
//
//import javafx.event.ActionEvent;
//
//public class MySceneController {
//	@FXML
//	private Button mybutton;
//	@FXML
//	private TextField myTextField;
//
//	// Event Listener on Button[#mybutton].onAction
//	@FXML
//	public void showDateTime(ActionEvent event) {
//		// TODO Autogenerated
//	}
//}
import java.net.URL;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.ResourceBundle;

import controller.Service;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;
import javafx.scene.control.ListView;
import javafx.scene.control.TextField;
import model.program_state.*;
import model.statement.Statement;
import my_exceptions.MyException;
import my_exceptions.TypeException;
import repository.IRepository;
import repository.Repository;

public class ProgramSelectorController implements Initializable {
    private static int count=0;

    @FXML
    private Button runButton;
    @FXML
    private TextField info;
    @FXML
    private ListView<Statement> programs;


    @Override
    public void initialize(URL location, ResourceBundle resources) {

        // TODO (don't really need to do anything here).
        runButton.setOnAction(event -> {
                    Statement statement=programs.getSelectionModel().getSelectedItem();
                    info.clear();
                    if(statement==null){return;}
                    try {
                        statement.typecheck(new TypeEnv());
                        Service service =createService(statement);
                        MainWindow mainWindow=new MainWindow(service);
                        mainWindow.open();
                    }
                    catch(TypeException e) {
                        //System.out.println("Type error: "+e.getMessage());//DEBUG
                        info.setText("Type error: "+e.getMessage());
                        info.setStyle("-fx-text-fill: red;");

                    }
                    catch(MyException e) {
                        info.setText("Type error: "+e.getMessage());
                        info.setStyle("-fx-text-fill: red;");

                    }
        });
    }

    private Service createService(Statement statement){
            //construct program state, repo and service dynamically
            ExecutionStack executionStack = new ExecutionStack();
            executionStack.push(statement);
            PrgState prg=new PrgState(executionStack,new SymTable(), new Heap(), new Output(), new FileTable());

            String filepath="files/log";

            filepath+=Integer.toString(++count)+".txt";
            //filepath+='('+count+')'+".txt";

            IRepository repo=new Repository(prg,filepath);
            Service service=new Service(repo);
            return service;
        }

}